name: Auto tag on version change

on:
  push:
    paths:
      - getfscaler/_metadata.py

jobs:
  autotag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract version
        id: get_version
        run: |
          echo "version=v$(python -c 'import importlib; print(importlib.import_module("getfscaler._metadata").__version__)')" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: ${{ steps.get_version.outputs.version }}

      - name: Make tag
        uses: actions/github-script@v8
        if: steps.check_tag.outputs.exists == 'false'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.get_version.outputs.version }}`,
              sha: context.sha
            })

      - name: Fallback
        if: steps.check_tag.outputs.exists == 'true'
        run: echo "Nothing to see here, move along citizen"

  webhook:
    needs: autotag
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - name: Get context
        uses: qoomon/actions--context@v5
        id: context

      - name: Get branch
        id: branch
        run: echo "current_branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Send Discord webhook (only on failure)
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-url: ${{ steps.context.outputs.job_html_url }}
          embed-title: "[${{ github.event.repository.name }}] ${{ steps.context.outputs.job_name }} failed on ${{ steps.branch.outputs.current_branch }}"
          username: "GitHub - ${{ github.repository }}"
          avatar-url: https://github.githubassets.com/favicons/favicon.png
